server:
  port: 8081
#  servlet:
#    context-path: /ms-instructor
    
  error:
    include-details: always
    
# Oracle settings
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: PRUEBA
    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver