CREATE TABLE CUSTOMERS(
   ID_CUSTOMERS NUMERIC(10,0) NOT NULL PRIMARY KEY,
   NOMBRE varchar2(60) NOT NULL,
   APELLIDO varchar2(60) NOT NULL,
   EMAIL varchar2(30)  NULL,
   DNI varchar2(20) NOT NULL,
   FECHA_CREACION DATE  NULL ,   
   FECHA_NACIMIENTO DATE  NULL
   
);

CREATE SEQUENCE SEQ_CUSTOMERS;


GROUP BY to_char(FECHA_NACIMIENTO, 'MM/YYYY')
